### PR TITLE
Add support for in-place real transforms

### PR DESCRIPTION
**Pull request by SyamGadde**
This is a proposed change to allow in-place real-to-complex/complex-to-real transforms.  The user specifies a view of the input array (using the target data type) as the output and `FFT()` will recognize it as the same data buffer.  Since real transforms require padding on the real side, I added in_shape (for real-to-complex) and out_shape (for complex-to-real) to specify the shape of the leading portion of the array that is (or will be) filled with valid data.  A nice side effect of this approach is that you can send arrays that are arbitrarily end-padded in any dimension, which (I think!) will now give users the ability to specify all the possible array shape/strides patterns supported by clFFT.

Side note: If you mandate an out_array for all 'real' transforms (forward and backward, in-place and out-of-place), then you can eliminate the 'real' boolean keyword argument because `__init__()` can easily check the datatypes of the in/out arrays.

Usage (in-place works best with order='F' arrays because view() works correctly then):
```
import numpy as np
import pyopencl as cl
import pyopencl.array as cla
from gpyfft.fft import FFT

context = cl.create_some_context()
queue = cl.CommandQueue(context)

in_type = np.float32
out_type = np.complex64
m = 4; n = 4
shape = [m,n]
padshape = [2 * ((m // 2) + 1), n]

# real-to-complex
x_in = np.zeros(padshape, dtype=in_type, order='F')
x_in[:m, :n] = np.arange(16, dtype=in_type).reshape([4,4])
x_in_gpu = cla.to_device(queue, x_in)
x_out_gpu = x_in_gpu.view(np.complex64) # same underlying buffer
transform = FFT(context, queue, x_in_gpu, axes = (0, 1), in_shape=shape, out_array=x_out_gpu)
event, = transform.enqueue()
event.wait()
result_host = x_out_gpu.get()

# complex-to-real
transform = FFT(context, queue, x_out_gpu, axes = (0, 1), real=True, out_shape=shape, out_array=x_in_gpu)
event, = transform.enqueue(forward=False)
event.wait()
result_host2 = x_in_gpu.get()

assert np.allclose(x_in[:m, :n], result_host2[:m, :n])
```

### CODE REVIEW

**Comment by geggo** [comment]
thanks, looks good, I'll give it a try!

**Comment by geggo** [comment]
Hi Syam,

tried it, but ran into troubles. Could you please provide an example of how to use inplace real-to-complex transforms, e.g for a 1D array. 

For the moment I reverted the changes on the master branch (probably not the right git way), your PR changes live now on the inline-real-to-complex branch.

Gregor

**Comment by SyamGadde** [comment]
Sure thing -- I was actually about to put an example here but then I realized you had alrady merged it. :-)  Let me make sure to be in sync with the current master and I'll see if I need to change anything before sending an example.

**Comment by geggo** [comment]
Hi Syam,

got inspired by your work and contemplated more about inplace transforms. Finally I figured out that just a few lines are sufficient to support them with current master.  More on my thoughts and examples
https://gist.github.com/geggo/6bbc597439ffbec596353cf699fb025c
Still rough, but works for me.
Gregor

**Comment by SyamGadde** [comment]
Thanks for putting together those notes, I think they reflect the main issues well.  I'll add some thoughts to that separately.  Also, I know you added a solution in master, just putting this example for my branch (which corresponds I guess to Option 1 in your notes) for completeness.  I'll test out master and give feedback soon.

```
import numpy as np
import pyopencl as cl
import pyopencl.array as cla
import random
from gpyfft.fft import FFT
context = cl.create_some_context()
queue = cl.CommandQueue(context) 
in_type = np.float32
out_type = np.complex64

for order in ('F', 'C'):
    for axes in ((0,1), (1,0)):
        fastestdim = int(order == 'C')
        if axes[0] == fastestdim:
            print "=== THESE SHOULD ALL WORK ==="
        else:
            # if real-transform axis is not the fastest dimension then
            # all bets are off.  Don't know yet why some work and others
            # don't.
            print "=== SOME OF THESE WILL FAIL ==="
        for it in range(20):
            m = random.randrange(2, 12, 2)
            n = random.randrange(2, 12, 2)
            print "order=%s axes=%s (%d x %d) " % (order, axes, m, n),
            shape = [m,n]
            padshape = list(shape)
            if axes[0] == fastestdim:
                # first transformed axis (real-transform) is the fastest dim
                # need (N // 2) + 1 elements total
                padshape[fastestdim] += 2
            else:
                # need 2 * N elements total, but still doesn't work some times
                padshape[fastestdim] *= 2
            outslice = [slice(0, m), slice(0, n)]
            outslice[axes[0]] = slice(0, (outslice[axes[0]].stop // 2) + 1)
            outslice = tuple(outslice)
            x_in = np.zeros(padshape, dtype=in_type, order=order)
            x_in[:m, :n] = np.arange(1, (m * n) + 1, dtype=in_type).reshape([m,n], order=order)
            x_in_gpu = cla.to_device(queue, x_in)
            x_out_gpu = x_in_gpu.view(np.complex64)
            x_sub = x_in_gpu[:m, :n]
            #print "x_in_gpu.shape=%s" % (x_in_gpu.shape,)
            #print "x_in_gpu.strides=%s" % (x_in_gpu.strides,)
            #print "x_out_gpu.shape=%s" % (x_out_gpu.shape,)
            #print "x_sub.shape=%s" % (x_sub.shape,)
            #print "outslice=%s" % (outslice,)
            transform = FFT(context, queue, x_sub, axes=axes, real=True)
            event, = transform.enqueue()
            event.wait()
            x_out_gpu = x_in_gpu.view(np.complex64)
            result_host = x_out_gpu.get()[outslice]
            result_numpy = np.fft.rfftn(x_in[:m, :n], axes=axes[::-1])
            #print "x_in (zeros are padding)\n", x_in
            #print "gpyfft: fft(x_in)\n", result_host
            #print "numpy: rfft(x_in)\n", result_numpy
            if not np.allclose(result_host, result_numpy, atol=np.max(x_in)*1e-05):
                print "FAIL FORWARD: max abs diff: %s" % (np.max(np.abs(result_numpy - result_host)),)
                continue
    
            transform = FFT(context, queue, x_out_gpu[outslice], axes=axes, fft_shape=(m, n), real=True)
            event, = transform.enqueue(forward=False)
            event.wait()
            result_host2 = x_in_gpu.get()[:m, :n]
            #print "x_in[:m,:n]\n", x_in[:m, :n]
            #print "gpyfft: ifft(fft(x_in))\n", result_host2
            if not np.allclose(x_in[:m, :n], result_host2, atol=np.max(x_in)*1e-05):
                print "FAIL REVERSE: max abs diff: %s" % (np.max(np.abs(x_in[:m, :n] - result_host2)),)
                continue

            print "SUCCESS"
```

**Pull request merged**
